development:
    cloudinary_cloud_name: ddf1eqd29
    cloudinary_api_key: 426288811446363
    cloudinary_api_secret: b_alWfismzTFX71522sXxecOsmM
    secret_key_base: 86a74583b359c363711c5b2ba0b75ad44f08900376091b91aed8e73195e1b37a86d3e8f7ea4c239c7c95f9719228b03a5f38092fb4affcca70a74235485f3db5
    sendgrid_apikey: <%= ENV['SENDGRID_APIKEY'] %>
    chatbot_access_token: <%= ENV["CHATBOT_ACCESS_TOKEN"] %>
    stripe_secret_key: <%= ENV['SECRET_KEY'] %>
    stripe_publishable_key: <%= ENV['PUBLISHABLE_KEY'] %>
test:
    cloudinary_cloud_name: ddf1eqd29
    cloudinary_api_key: 426288811446363
    cloudinary_api_secret: b_alWfismzTFX71522sXxecOsmM
    secret_key_base: 86a74583b359c363711c5b2ba0b75ad44f08900376091b91aed8e73195e1b37a86d3e8f7ea4c239c7c95f9719228b03a5f38092fb4affcca70a74235485f3db5
    sendgrid_apikey: <%= ENV['SENDGRID_APIKEY'] %>
    chatbot_access_token: <%= ENV["CHATBOT_ACCESS_TOKEN"] %>
    stripe_secret_key: <%= ENV['SECRET_KEY'] %>
    stripe_publishable_key: <%= ENV['PUBLISHABLE_KEY'] %>

production:
    cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
    cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
    cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
    secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
    sendgrid_apikey: <%= ENV['SENDGRID_APIKEY'] %>
    chatbot_access_token: <%= ENV["CHATBOT_ACCESS_TOKEN"] %>
    stripe_secret_key: <%= ENV['SECRET_KEY'] %>
    stripe_publishable_key: <%= ENV['PUBLISHABLE_KEY'] %>
